- name: Hosts
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/environment.yml
    - vars/service_account.yml

  tasks:
    - name: Provisioning
      tags:
        - vm
      block:
        - name: Ping VM
          ansible.builtin.ping:
          register: res_ping
          ignore_unreachable: true
          ignore_errors: true

        - ansible.builtin.include_tasks: tasks/provision_vm.yml
          when: ((vm_update is defined) and vm_update) or (((res_ping.unreachable is defined) or (res_ping is failed)) and (vm_state == "present")) or ((res_ping.unreachable is not defined) and (vm_state == "absent"))

    - name: Gather facts after provisioning
      ansible.builtin.setup: