- name: Hosts
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/environment.yml
    - vars/service_account.yml

  tasks:
    - name: Provisioning
      tags:
        - vm
      block:
        - name: Ping VM
          ansible.builtin.ping:
          register: res_ping
          ignore_unreachable: true
          ignore_errors: true

        - ansible.builtin.include_tasks: tasks/provision_vm.yml
          when: ((vm_update is defined) and vm_update) or (((res_ping.unreachable is defined) or (res_ping is failed)) and (vm_state == "present")) or ((res_ping.unreachable is not defined) and (vm_state == "absent"))

    - name: Gather facts after provisioning
      ansible.builtin.setup:

    - name: apt is updated
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes

    - name: "Temporary installation folder {{ temporary_intallation_directory }}"
      ansible.builtin.file:
        path: "{{ temporary_intallation_directory }}"
        state: directory
        owner: "{{ service_account.username }}"

    - name: Time synchronisation using NTP
      block:
        - name: Configure NTP
          ansible.builtin.lineinfile:
            path: /etc/systemd/timesyncd.conf
            regexp: '^#{{ item.ntp_key }}'
            line: "{{ item.ntp_key }}={{ item.ntp_value }}"
          loop:
            - {ntp_key: "NTP", ntp_value: "0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org"}
            - {ntp_key: "FallbackNTP", ntp_value: "0.pool.ntp.org 1.pool.ntp.org 0.fr.pool.ntp.org"}

        - name: Restart NTP daemon
          ansible.builtin.systemd_service:
            name: systemd-timesyncd
            state: restarted
            enabled: yes
