vm:
  prefix: example
  tag: k3s

temporary_intallation_directory:  /opt/install

service_account:
  username: service

k3s_version: "v1.32.2-rc1+k3s1"

cluster:
  name: "{{ vm.prefix }}-{{ vm.tag }}"
  ingress_vip: "192.168.10.10"
  apiserver_vip: "192.168.10.11"
  apiserver_port: 6443

server:
  directory: /var/lib/rancher/k3s
  config_file: /etc/rancher/k3s/config.yaml
  config:
    write-kubeconfig-mode: "0644"
    tls-san:
      - "https://{{ cluster.apiserver_vip }}.sslip.io"
      - "{{ cluster.apiserver_vip }}"
    node-label:
      - "role={{ ansible_host | regex_search('(?<=' + vm.tag + '-)[a-z]*') }}"
    cluster-cidr: "192.168.0.0/16"
    flannel-backend: none
    disable-network-policy: true
    disable:
      - traefik
      - servicelb

kubeconfig: /home/{{ service_account.username }}/kubeconfig_{{ vm.tag }}.yml

kubeseal_version: "0.29.0"

calico_nodemetrics_port: 9093
calico_typhametrics_port: 9094

metallb_version: "v0.14.9"
