---
- ansible.builtin.import_playbook: ../create_basevm.yml
  tags:
    - provision

- name: Deploy k3s
  hosts: k3s_services
  gather_facts: true
  become: true
  vars:
    cluster_name: "services"
  vars_files:
    - ../vars/environment.yml
    - ../vars/service_account.yml
    - vars/k3s.yml

  tasks:
    - ansible.builtin.include_role:
        name: prepare

    - ansible.builtin.include_role:
       name: k3s

    - ansible.builtin.include_role:
        name: longhorn

    - name: Portainer
      when: inventory_hostname == groups.services_control[0]
      become: false
      block:
        - ansible.builtin.include_role:
            name: k3s
            tasks_from: docker_secret.yml
          vars:
            secret_namespace: portainer

        - name: Add Portainer repo
          kubernetes.core.helm_repository:
            name: portainer
            repo_url: "https://portainer.github.io/k8s"

        - name: Install Portainer # MUST match https://github.com
          kubernetes.core.helm:
            kubeconfig: "{{ kubeconfig }}"
            name: portainer
            chart_ref: portainer/portainer
            chart_version: 
            release_namespace: portainer
            create_namespace: true
            values:
              imagePullSecrets:
                - name: docker-secret
              persistence:
                size: "1Gi"
            wait: true