---
- ansible.builtin.import_playbook: ../create_basevm.yml
  tags:
    - provision

- name: Deploy k3s
  hosts: k3s_services
  gather_facts: true
  become: true
  vars:
    cluster_name: "services"
  vars_files:
    - ../vars/environment.yml
    - ../vars/service_account.yml
    - vars/k3s.yml

  tasks:
    - ansible.builtin.include_role:
        name: prepare

    - ansible.builtin.include_role:
       name: k3s

    - ansible.builtin.include_role:
        name: longhorn
