- name: Required packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - git
      - policycoreutils
    state: latest

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Populate service facts
  ansible.builtin.service_facts:
