openstack:
  network: diszlexia-mi-net
  initial_username: ubuntu
  initial_key: auer_tibor

organisation:
  vm_prefix: akk
  vm_tag_services: services

temporary_intallation_directory: /opt/install

projects_volume:
  name: projects
  size: 200 # GiB
  mount_location: "/projects"
