- name: Create secret definition
  ansible.builtin.template:
    src: templates/secret.j2
    dest: "{{ temporary_intallation_directory }}/tmp_secret.yml"

- name: Create sealed secret definition
  ansible.builtin.command: "kubeseal --format=yaml -f {{ temporary_intallation_directory }}/tmp_secret.yml -w {{ temporary_intallation_directory }}/tmp_secret_sealed.yml"
  environment:
    KUBECONFIG: "{{ kubeconfig_file | default(kubeconfig) }}"

- name: Create sealed secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_file | default(kubeconfig) }}"
    src: "{{ temporary_intallation_directory }}/tmp_secret_sealed.yml"

- name: Cleanup
  ansible.builtin.file:
    path: "{{ temporary_intallation_directory }}/{{ item }}"
    state: absent
  loop:
    - tmp_secret.yml
    - tmp_secret_sealed.yml
